default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: projectVFTD_development

test:
  <<: *default
  database: projectVFTD_test

production:
  <<: *default
  database: projectVFTD_production
  username: koan_dev
  password: <%= ENV['PROJECTVFTD_DATABASE_PASSWORD'] %>
